---
# Copyright 2026 by Ichiro Furusato. All rights reserved. This file is
# part of the krzos-ansible project, released under the MIT License.
# Please see the LICENSE file included as part of this package.
#
# author:   Ichiro Furusato
# created:  2026-03-18
# modified: 2026-03-18
#
# install-krzos.yml — clone KRZOS from GitHub Repository

- name: Install KRZOS from GitHub Repository
  hosts: all
  become: yes
  tasks:
    - name: Ensure workspaces directory exists
      file:
        path: /home/pi/workspaces/workspace-krzos
        state: directory
        owner: pi
        group: pi
        mode: '0755'

    - name: Clone KRZOS repo
      git:
        repo: 'git@github.com:ifurusato/krzos.git'
        dest: /home/pi/workspaces/workspace-krzos/krzos
        version: main
        force: yes
        accept_hostkey: yes
        key_file: /home/pi/.ssh/id_rsa  # Changed from id_rsa_github
      become_user: pi

#EOF
